Modul2Test_Vladimir_Asic/Models/Artikl.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Modul2Test_Vladimir_Asic.Models
{
    public enum Tip
    {
        Muski,
        Zenski,
        Deciji
    }

    public class Artikl
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Niste uneli naziv")]
        public string Naziv { get; set; }

        public Tip Tip { get; set; }

        [Required(ErrorMessage = "Niste uneli cenu")]
        [Range(0.1, Double.MaxValue, ErrorMessage = "Vrednost mora biti veca od 0")]
        public decimal Cena { get; set; }

        [Required(ErrorMessage = "Niste uneli marku")]
        public string Marka { get; set; }

        [Required(ErrorMessage = "Niste uneli opis")]
        [StringLength(200, MinimumLength = 3, ErrorMessage = "Uneli ste manje od 10 karaktera")]
        public string Opis { get; set; }

        public KategorijaArtikla KategorijaArtikla { get; set; }
        public bool Aktivan { get; set; } = true;
        public bool Akcija { get; set; }

        public Artikl()
        {
            this.KategorijaArtikla = new KategorijaArtikla();
        }

        public Artikl(int id, string naziv, Tip tip, decimal cena, string marka, string opis, bool aktivan, bool akcija) : this()
        {
            this.Id = id;
            this.Naziv = naziv;
            this.Tip = tip;
            this.Cena = cena;
            this.Marka = marka;
            this.Opis = opis;
            this.Aktivan = aktivan;
            this.Akcija = akcija;
        }
    }
}

Modul2Test_Vladimir_Asic/Models/KategorijaArtikla.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Modul2Test_Vladimir_Asic.Models
{
    public class KategorijaArtikla
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Niste uneli naziv")]
        public string Naziv { get; set; }
        //public List<Artikl> Artikl { get; set; }

        public KategorijaArtikla()
        {
            //this.Artikl = new List<Artikl>();
        }

        public KategorijaArtikla(int id, string naziv) /*: this()*/
        {
            this.Id = id;
            this.Naziv = naziv;
        }
    }
}

Modul2Test_Vladimir_Asic/ViewModels/ArtiklKategorijeArtiklaViewModels.cs
using Modul2Test_Vladimir_Asic.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Modul2Test_Vladimir_Asic.ViewModels
{
    public class ArtiklKategorijeArtiklaViewModels
    {
        public Artikl Artikl { get; set; }
        public List<Artikl> Artikli { get; set; }
        public List<KategorijaArtikla> KategorijeArtikla { get; set; }
        public int selectedKategorijaArtiklaId { get; set; }
        public bool Filtriraj { get; set; }
    }
}

Modul2Test_Vladimir_Asic/Controllers/ArtiklController.cs
using Modul2Test_Vladimir_Asic.Interfaces;
using Modul2Test_Vladimir_Asic.Models;
using Modul2Test_Vladimir_Asic.Repository;
using Modul2Test_Vladimir_Asic.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modul2Test_Vladimir_Asic.Controllers
{
    public class ArtiklController : Controller
    {
        private IArtiklRepository aRepository = new ArtiklRepository();
        private IKategorijaArtiklaRepository kaRepository = new KategorijaArtiklaRepository();

        // GET: Artikl
        public ActionResult Index()
        {
            ArtiklKategorijeArtiklaViewModels model = new ArtiklKategorijeArtiklaViewModels();
            model.Artikli = aRepository.GetAll();
            foreach (var item in model.Artikli)
            {
                var res = kaRepository.GetById(item.KategorijaArtikla.Id);
                item.KategorijaArtikla = res;
            }
            model.KategorijeArtikla = kaRepository.GetAll();
            //model.ProsecnaOcena = pRepository.ProsecnaOcena();
            //model.ProsecnaOcena = model.Piva.Average(p => p.Ocena);
            model.Artikli = model.Artikli.Where(a => a.Aktivan).ToList();
            return View(model);
        }

        // POST: Artikl
        [HttpPost]
        public ActionResult Create(ArtiklKategorijeArtiklaViewModels model)
        {
            model.Artikl.KategorijaArtikla = kaRepository.GetById(model.selectedKategorijaArtiklaId);
            if (ModelState.IsValid)
            {
                //model.Artikl.KategorijaArtikla.Id = model.selectedKategorijaArtiklaId;
                var res = aRepository.Create(model.Artikl);
                if (res)
                {
                    return RedirectToAction("Index");
                }
            }

            model.Artikli = aRepository.GetAll();
            foreach (var item in model.Artikli)
            {
                var res = kaRepository.GetById(item.KategorijaArtikla.Id);
                item.KategorijaArtikla = res;
            }
            model.KategorijeArtikla = kaRepository.GetAll();

            return View("Index", model);
        }

        // GET: Pivo
        [HttpPost]
        public ActionResult Delete(int id)
        {
            Artikl artikl = new Artikl();
            artikl = aRepository.GetById(id);
            artikl.Aktivan = false;
            if (ModelState.IsValid)
            {
                var res = aRepository.Update(artikl);
                if (res)
                {
                    return RedirectToAction("Index");
                }
            }

            ArtiklKategorijeArtiklaViewModels model = new ArtiklKategorijeArtiklaViewModels();
            model.Artikli = aRepository.GetAll();
            foreach (var item in model.Artikli)
            {
                var res = kaRepository.GetById(item.KategorijaArtikla.Id);
                item.KategorijaArtikla = res;
            }
            model.KategorijeArtikla = kaRepository.GetAll();
            model.Artikli = model.Artikli.Where(a => a.Aktivan).ToList();
            return View("Index", model);
        }

        // GET: Artikl/1
        public ActionResult Edit(int id)
        {
            ArtiklKategorijeArtiklaViewModels model = new ArtiklKategorijeArtiklaViewModels();
            model.Artikl = aRepository.GetById(id);
            model.KategorijeArtikla = kaRepository.GetAll();
            return View(model);
        }

        // POST: Artikl/1
        [HttpPost]
        public ActionResult Edit(ArtiklKategorijeArtiklaViewModels model)
        {
            model.Artikl.KategorijaArtikla = kaRepository.GetById(model.selectedKategorijaArtiklaId);
            if (ModelState.IsValid)
            {
                var res = aRepository.Update(model.Artikl);
                if (res)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        // GET: Artikl/1
        public ActionResult Filter(ArtiklKategorijeArtiklaViewModels model)
        {
            if (!model.Filtriraj)
            {
                return RedirectToAction("Index");
            }
            else
            {
                model.Artikli = aRepository.GetAll();
                model.Artikli = model.Artikli.Where(a => a.Aktivan).ToList();
                model.Artikli = model.Artikli.Where(a => a.Akcija == true).ToList();
                foreach (var item in model.Artikli)
                {
                    var res = kaRepository.GetById(item.KategorijaArtikla.Id);
                    item.KategorijaArtikla = res;
                }
                model.KategorijeArtikla = kaRepository.GetAll();
                return View("Index", model);
            }
        }
    }
}

Modul2Test_Vladimir_Asic/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Modul2Test_Vladimir_Asic.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Modul2Test_Vladimir_Asic/Views/Artikl/Edit.cshtml
@model Modul2Test_Vladimir_Asic.ViewModels.ArtiklKategorijeArtiklaViewModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <meta charset="utf-8" />                                            @* ### Ja sam dodao ### *@
    <link href="~/Content/ProdavnicaOdece.css" rel="stylesheet" />      @* ### Ja sam dodao ### *@
    <script src="~/Scripts/jquery-1.10.2.js"></script>                  @* ### Ja sam dodao ### *@
    <script src="~/Scripts/ProdavnicaOdeceScript.js"></script>          @* ### Ja sam dodao ### *@
</head>
<body>
    <div>
        @using (Html.BeginForm("Edit", "Artikl", FormMethod.Post, new { id = "forma1" }))
    {
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-md-10">
                    @Html.ValidationSummary()
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.HiddenFor(m => m.Artikl.Id, new { @class = "prodavnicaOdece1" })
                    @Html.ValidationMessageFor(m => m.Artikl.Id, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.Artikl.Akcija, new { @class = "prodavnicaOdece1" })
                    @Html.EditorFor(m => m.Artikl.Akcija)
                    @Html.ValidationMessageFor(m => m.Artikl.Akcija, "", new { @class = "text-danger" })
                    @*<span id="PivoNazivSpan"></span>*@
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.Artikl.Naziv, new { @class = "prodavnicaOdece1" })
                    @Html.EditorFor(m => m.Artikl.Naziv)
                    @Html.ValidationMessageFor(m => m.Artikl.Naziv, "", new { @class = "text-danger", id = "naziv1" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.Artikl.Cena, new { @class = "prodavnicaOdece1" })
                    @Html.EditorFor(m => m.Artikl.Cena)
                    @Html.ValidationMessageFor(m => m.Artikl.Cena, "", new { @class = "text-danger", id = "cena1" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.Artikl.Marka, new { @class = "prodavnicaOdece1" })
                    @Html.EditorFor(m => m.Artikl.Marka)
                    @Html.ValidationMessageFor(m => m.Artikl.Marka, "", new { @class = "text-danger", id = "marka1" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.Artikl.Opis, new { @class = "prodavnicaOdece1" })
                    @Html.EditorFor(m => m.Artikl.Opis)
                    @Html.ValidationMessageFor(m => m.Artikl.Opis, "", new { @class = "text-danger", id = "opis1" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.Artikl.Tip, new { @class = "prodavnicaOdece1" })
                    @Html.EnumDropDownListFor(m => m.Artikl.Tip, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    @Html.LabelFor(m => m.KategorijeArtikla.FirstOrDefault().Naziv, new { @class = "prodavnicaOdece1" })
                    @Html.DropDownListFor(m => m.selectedKategorijaArtiklaId,
                    new SelectList(Model.KategorijeArtikla, "Id", "Naziv"))
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 prodavnicaOdece2">
                    <input type="submit" value="Submit" class="btn btn-default prodavnicaOdece3" />
                </div>
            </div>
        </div>
}
    </div>
</body>
</html>

Modul2Test_Vladimir_Asic/Views/Artikl/Index.cshtml
@model Modul2Test_Vladimir_Asic.ViewModels.ArtiklKategorijeArtiklaViewModels
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta charset="utf-8" />                                            @* ### Ja sam dodao ### *@
    <link href="~/Content/ProdavnicaOdece.css" rel="stylesheet" />      @* ### Ja sam dodao ### *@
    <script src="~/Scripts/jquery-1.10.2.js"></script>                  @* ### Ja sam dodao ### *@
    <script src="~/Scripts/ProdavnicaOdeceScript.js"></script>          @* ### Ja sam dodao ### *@
</head>
<body>
    <div>
        @using (Html.BeginForm("Create", "Artikl", FormMethod.Post, new { id = "forma1" }))
        {
            <div class="form-horizontal">
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.ValidationSummary()
                        @*@Html.HiddenFor(m => m.Artikl.Id)*@
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.Artikl.Akcija, new { @class = "prodavnicaOdece1" })
                        @Html.EditorFor(m => m.Artikl.Akcija)
                        @Html.ValidationMessageFor(m => m.Artikl.Akcija, "", new { @class = "text-danger" })
                        @*<span id="PivoNazivSpan"></span>*@
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.Artikl.Naziv, new { @class = "prodavnicaOdece1" })
                        @Html.EditorFor(m => m.Artikl.Naziv)
                        @Html.ValidationMessageFor(m => m.Artikl.Naziv, "", new { @class = "text-danger", id = "naziv1" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.Artikl.Cena, new { @class = "prodavnicaOdece1" })
                        @Html.EditorFor(m => m.Artikl.Cena)
                        @Html.ValidationMessageFor(m => m.Artikl.Cena, "", new { @class = "text-danger", id = "cena1" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.Artikl.Marka, new { @class = "prodavnicaOdece1" })
                        @Html.EditorFor(m => m.Artikl.Marka)
                        @Html.ValidationMessageFor(m => m.Artikl.Marka, "", new { @class = "text-danger", id = "marka1" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.Artikl.Opis, new { @class = "prodavnicaOdece1" })
                        @Html.EditorFor(m => m.Artikl.Opis)
                        @Html.ValidationMessageFor(m => m.Artikl.Opis, "", new { @class = "text-danger", id = "opis1" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.Artikl.Tip, new { @class = "prodavnicaOdece1" })
                        @Html.EnumDropDownListFor(m => m.Artikl.Tip, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        @Html.LabelFor(m => m.KategorijeArtikla.FirstOrDefault().Naziv, new { @class = "prodavnicaOdece1" })
                        @Html.DropDownListFor(m => m.selectedKategorijaArtiklaId,
                            new SelectList(Model.KategorijeArtikla, "Id", "Naziv"))
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10 prodavnicaOdece2">
                        <input type="submit" value="Submit" class="btn btn-default prodavnicaOdece3" />
                    </div>
                </div>
            </div>
        }
    </div>

    <br />

    @if (Model.Filtriraj)
    {
        using (Html.BeginForm("Filter", "Artikl"))
        {
    <button type="submit" name="@Html.NameFor(m => m.Filtriraj)" value="false">Ugasi filter</button>
        }
    }
    else
    {
        using (Html.BeginForm("Filter", "Artikl"))
        {
            <button type="submit" name="@Html.NameFor(m => m.Filtriraj)" value="true">Filtriraj po akciji</button>
        }
    }

    <br />

    <div>
        @foreach (var item in Enum.GetValues(typeof(Modul2Test_Vladimir_Asic.Models.Tip)))
        {
            <table class="table table-striped" border="1">
                <thead class="thead-dark">
                    <tr>
                        <th colspan="5"><b>@item.ToString() Kolekcija</b></th>
                    </tr>
                    <tr>
                        <th scope="col">Kategorija</th>
                        <th scope="col">Naziv i opis</th>
                        <th scope="col">Cena</th>
                        <th scope="col" colspan="2"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var artikal in Model.Artikli)
                    {
                        if (artikal.Tip.ToString() == item.ToString())
                        {
                            <tr>
                                <td>@Html.DisplayFor(Model => artikal.KategorijaArtikla.Naziv)</td>
                                <td>@Html.DisplayFor(Model => artikal.Naziv)</td>
                                <td>@Html.DisplayFor(Model => artikal.Cena)</td>
                                <td>
                                    <form action="\artikl\Delete" method="post">
                                        <input type="hidden" name="id" value="@artikal.Id" />
                                        <input type="submit" value="Obrisi" />
                                    </form>
                                </td>
                                <td>@Html.ActionLink("Izmeni", "Edit", "Artikl", new { id = artikal.Id }, null)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>

            <br />

        }
    </div>
</body>
</html>

Modul2Test_Vladimir_Asic/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Modul2Test_Vladimir_Asic/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Modul2Test_Vladimir_Asic/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Modul2Test_Vladimir_Asic/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>